blog/urls.py
from django.urls import path

from . import views
from .rss_feeds import LatestArticlesFeed
from .views import (ArticleDeleteView, ArticleListView, UpdateArticleView,
                    UserArticleListView, search_article)

app_name = 'article'
urlpatterns = [
    path('feed/', LatestArticlesFeed(), name='article_feed'),
    path('search/', search_article, name='search_articles'),
    path('create/', views.create_article, name="create-article"),
    path('<slug:slug>/share/', views.post_share, name='post_share'),
    path('<slug:slug>/update/', UpdateArticleView.as_view(), name="update-post"),
    path('<slug:slug>/delete/', ArticleDeleteView.as_view(), name="delete-post"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.article_detail, name='article_detail'),
    path('all/', ArticleListView.as_view(), name="all-articles"),
    path('all/<str:category>', ArticleListView.as_view(), name="articles-by-category"),
    path('all/<slug:tag>', ArticleListView.as_view(), name="articles-by-slug"),
    path('<str:username>/', UserArticleListView.as_view(), name="article-by-user"),
]

blog/models.py
import uuid

from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager

from user.models import UserProfile


class Categories(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
    title = models.CharField(max_length=255, verbose_name="Title", default='UNCATEGORIZED')

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['title']

    def __str__(self):
        return self.title


class PublishedManager(BaseUserManager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=True, is_deleted=False).order_by('-publish_date')


class Article(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    article_title = models.CharField(max_length=100, null=False, blank=False)
    article_excerpt = models.CharField(max_length=255, null=True, blank=True)
    article_slug = models.SlugField(null=False, unique=True, max_length=150)
    article_content = models.TextField()
    feature_img = models.ImageField(upload_to='article_feature_img', default='feature_default.jpg')
    article_author = models.ForeignKey(UserProfile,
                                       on_delete=models.CASCADE,
                                       null=True,
                                       blank=True,
                                       related_name="user_article")
    category = models.ManyToManyField(Categories, blank=True, verbose_name="Category", related_name="article")
    is_published = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    publish_date = models.DateTimeField(default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="Created_at")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="Updated_at")

    published = PublishedManager()
    objects = models.Manager()
    tags = TaggableManager()

    def __str__(self):
        return self.article_title

    def get_absolute_url(self):
        return reverse('article:article_detail',
                       args=[self.publish_date.year,
                             self.publish_date.month,
                             self.publish_date.day,
                             self.article_slug])

    def to_dict(self):
        return {
            'uuid': str(self.uuid),
            # 'article_title': self.article_title,
            'article_slug': self.article_slug,
            # 'article_content': self.article_content,
            'feature_img': self.feature_img.url if self.feature_img else None,
            'article_author': self.article_author.get_full_name() if self.article_author else None,
            'category': [category.title for category in self.category.all()],
            'is_published': self.is_published,
            'is_deleted': self.is_deleted,
            # 'publish_date': self.publish_date.isoformat(),
            # 'date_created': self.date_created.isoformat(),
            # 'date_updated': self.date_updated.isoformat(),
            'tags': list(self.tags.names()),
        }


#     override save method to autogenerate slug

class Comments(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    website = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'


class InnerComments(models.Model):
    post = models.ForeignKey(Comments, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    # website = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return f'reply {self.body} to {self.post}'

blog/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.template.defaultfilters import slugify

from .models import Article, Categories, Comments


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('name', 'email', 'body', 'website')


class ArticleForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget = forms.CheckboxSelectMultiple()
        self.fields['category'].queryset = Categories.objects.all()

        if self.instance.pk:
            self.initial['tags'] = ', '.join(self.instance.tags.names())
            self.initial['category'] = self.instance.category.values_list('id', flat=True)

    class Meta:
        model = Article
        fields = ('feature_img', 'article_title', 'article_content', 'tags', 'category')
        widgets = {
            'article_content': CKEditorWidget(config_name='article'),
        }

    def clean(self):
        cleaned_data = super().clean()

        selected_categories = cleaned_data.get("category")
        if selected_categories:
            if selected_categories and len(selected_categories) > 4:
                self.add_error('category', "You can select a maximum of 4 categories.")
        return cleaned_data

    def save(self, commit=True):
        article = super().save(commit=False)
        slug = slugify(article.article_title)
        article.article_slug = slug
        if commit:
            article.save()
            self.save_m2m()
        return article


class EmailShareForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector)
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import DeleteView, ListView, UpdateView
from taggit.models import Tag

from blog.forms import ArticleForm, CommentForm, EmailShareForm, SearchForm
from blog.models import Article, Categories
# Get an instance of a logger
from ext_libs.sendgrid.sengrid import send_email
from utils.views import custom_paginator, get_actual_template

logger = logging.getLogger(__name__)


# Post Page Fxn recreated into a class
class ArticleListView(ListView):
    model = Article
    context_object_name = 'objects'
    ordering = ['-date_created']
    paginate_by = 3
    template_name = 'blog/article_list.html'
    tag = None
    category = None

    def get_queryset(self):
        queryset = Article.published.all()
        if self.kwargs.get('tag'):
            self.tag = get_object_or_404(Tag, slug=self.kwargs.get('tag'))
            queryset = queryset.filter(tags__in=[self.tag])
        if self.kwargs.get('category'):
            queryset = queryset.filter(category__title=self.kwargs.get('category'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = self.tag
        context['posts'] = self.get_queryset()
        context['recent_posts'] = self.get_queryset().order_by("-date_created")[:8]
        return context

    def get_template_names(self):
        template_names = super().get_template_names()
        return get_actual_template(self, 'blog/article_ajax.html') + template_names

    def paginate_queryset(self, queryset, page_size):
        return custom_paginator(self.request, page_size, queryset)


class UserArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'blog/article_list.html'
    context_object_name = 'objects'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(get_user_model(), username=self.kwargs.get('username'))
        articles = Article.objects.filter(article_author=user).order_by('-date_created')
        return articles


def get_similar_articles(article, limit=3):
    article_tags_ids = article.tags.values_list('id', flat=True)
    similar_articles = Article.objects.filter(tags__in=article_tags_ids).exclude(id=article.id)
    return similar_articles.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish_date')[:limit]


def article_detail(request, year, month, day, slug):
    template_name = 'blog/article_detail.html'
    article = get_object_or_404(Article, article_slug=slug,
                                publish_date__year=year,
                                publish_date__month=month,
                                publish_date__day=day)
    comments = article.comments.filter(active=True)
    similar_articles = get_similar_articles(article)
    posted_comment = None
    if request.method == 'POST':
        comment = CommentForm(request.POST)
        if comment.is_valid():
            new_comment = comment.save(commit=False)
            new_comment.post = article
            new_comment.save()
            if new_comment.id:
                messages.info(
                    request, 'Your comment has been posted and is awaiting moderation')
            else:
                messages.error(
                    request, 'Your comment was not posted, try again later')
            return HttpResponseRedirect(request.headers.get('referer'))
        else:
            logger.error(msg=str(comment.errors))
        messages.error(request, 'Form not fully filled, please retry.')
        return HttpResponseRedirect(request.headers.get('referer'))
    else:
        # comment_form = CommentForm()
        return render(request, template_name, {
            'article': article,
            'comments': comments,
            'new_comment': posted_comment,
            'similar': similar_articles,
        })


def search_article(request):
    form = SearchForm()
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    query = request.GET.get('query')
    results = []
    page = request.GET.get('page')
    context = {'form': form,
               'page': page,
               'query': query}
    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = \
                SearchVector('article_title', weight='A') + SearchVector('article_excerpt', weight='C') + \
                SearchVector('article_content', weight='C') + SearchVector('article_author__username', weight='D') + \
                SearchVector('article_author__first_name', weight='B') + SearchVector('article_author__last_name',
                                                                                      weight='B')
            search_query = SearchQuery(query)
            results = Article.published.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.2).order_by('-rank')
        paginator = Paginator(results, 2)
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            if is_ajax:
                return HttpResponse('')
            results = paginator.page(paginator.num_pages)
        if is_ajax:
            context['objects'] = results
            context['query'] = query
            context['pager'] = False
            return render(request, 'blog/search_result_ajax.html', context)
    context['objects'] = results
    return render(request, 'blog/search_page.html', context)


@login_required
def create_article(request):
    template_name = 'blog/article_form.html'

    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)

        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.article_author = request.user
            article.save()

            for category in article_form.cleaned_data['category']:
                new_category_instance, _ = Categories.objects.get_or_create(title=category)
                article.category.add(new_category_instance)

            article_form.save_m2m()
            return redirect('article:all-articles')

        article_errors = article_form.errors
        logger.error(article_errors)
    else:
        article_form = ArticleForm()

    context = {
        'form': article_form,
        'action_to_perform': "create new"
    }
    return render(request, template_name, context)


class UpdateArticleView(UserPassesTestMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/article_form.html'
    slug_url_kwarg = 'slug'
    slug_field = 'article_slug'

    def form_valid(self, form):
        form.instance.article_author = self.request.user
        image_field = form.cleaned_data.get('image_field')
        if isinstance(image_field, InMemoryUploadedFile):
            form.instance.image_field.save(
                image_field.name,
                image_field,
                save=False
            )

        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.article_author:
            return True
        return False

    def get_success_url(self):
        article = self.get_object()
        slug = article.article_slug
        date = article.publish_date

        return reverse('article:article_detail', kwargs={'year': date.year,
                                                         'month': date.month,
                                                         'day': date.day,
                                                         'slug': slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_to_perform'] = "update"
        return context


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    model = Article
    template_name = 'blog/article_confirm_delete.html'
    context_object_name = 'post'
    success_url = 'article:all-articles'
    slug_field = 'article_slug'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.article_author:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        article = self.get_object()
        article.is_deleted = True
        article.save()
        return redirect(self.success_url)


# Create your views here.
@login_required()
def all_post(request):
    post = Article.objects.all()
    return render(request, 'all-post.html', {'post': post})


# Create your views here.
@login_required()
def single_post(request):
    return render(request, 'article_detail.html')


# Create your views here.
def about(request):
    return render(request, 'about.html')


# remove if field later for uuid from calling function
# add option to share pot on FB, Twitter and IG

templates/blog/article_ajax.html
{% for article in objects %}
<article class="blog_item">
    <div class="blog_item_img">
        <a href="{{ article.get_absolute_url }}">
            <div id="yes"
                 style="background:transparent no-repeat center;background-size: cover;
                            background-image: url('{% if article.feature_img %}{{ article.feature_img.url }}{%endif%}');
                            transition: all .5s;"></div>
        </a><img class="card-img rounded-0" src="
                                    {% if article.feature_img %}{{ article.feature_img.url }}{%endif%}"
                 alt="">
        <a href="{{ article.get_absolute_url }}" class="blog_item_date">
            <h3>{{ article.date_created | date:"d" }}</h3>
            <p>{{ article.date_created | date:"M" }}, {{ article.date_created | date:"Y" }}</p>
        </a>
    </div>
    <div class="blog_details">
        <a class="d-inline-block" href="{{ article.get_absolute_url  }}">
            <h2 class="blog-head" style="color: #2d2d2d;">{{article.article_title}}</h2>
        </a>
        <p>{{article.article_content|safe|truncatewords_html:30|linebreaks}}</p>
        <ul class="blog-info-link">
            <li>
                <a href="{% url 'article:article-by-user' article.article_author.username %}">Written
                    by
                    <i class="fa fa-user"></i> {{article.article_author.get_full_name}}</a>
            </li>
            <li class="tags">
                Tags:
                {% for tag in article.tags.all %}
                <a href="{% url 'article:articles-by-slug' tag.slug %}">
                    {{tag.slug}}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </li>
        </ul>
    </div>
</article>
{% endfor %}

templates/blog/latest.html
{% load static %}

{% if recent_articles %}
<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title" style="color: #2d2d2d;">Latest Post</h3>
    {% for post in recent_articles %}
    <div class="media post_item">
        <!--                                    <img src="{% static 'img/post/post_1.png' %}" alt="post">-->
        <!--                                    <img height="100px" width="100px" src="{{post.feature_img.url}}" alt="post">-->
        <div id="" style="height: 70px; width:70px; background:transparent no-repeat center;background-size: cover;
                                        background-image: url('{{post.feature_img.url}}');
                                        transition: all .5s;"></div>
        <div class="media-body">
            <a href="{{ post.get_absolute_url }}">
                <h3 style="color: #2d2d2d;">{{post.article_title}}</h3>
            </a>
            <p>{{ post.date_created | date:"d M" }}, {{ post.date_created | date:"Y" }}</p>
        </div>
    </div>
    {% endfor %}
</aside>
{%endif%}

{% if categories %}
<aside class="single_sidebar_widget post_category_widget">
    <h4 class="widget_title" style="color: #2d2d2d;">Category</h4>
    <ul class="list cat-list">
        {% for category in categories %}
        <li>
            <a href="{% url 'article:articles-by-category' category.title %}" class="d-flex">
                <p>{{category.title}}</p>
                <p>({{category.num_articles}})</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</aside>
{%endif%}

{% if tags %}
<aside class="single_sidebar_widget tag_cloud_widget">
    <h4 class="widget_title" style="color: #2d2d2d;">Tag Clouds</h4>
    <ul class="list">
        {% for tag in tags %}
        <li>
            <a href="{% url 'article:articles-by-slug' tag.slug %}">{{tag.name}}</a>
        </li>
        {% endfor %}
    </ul>
</aside>
{% endif %}

{% if newsletter %}
<aside class="single_sidebar_widget newsletter_widget">
    <h4 class="widget_title" style="color: #2d2d2d;">Newsletter</h4>
    <form action="#">
        <div class="form-group">
            <input type="email" class="form-control" onfocus="this.placeholder = ''"
                   onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                type="submit">Subscribe
        </button>
    </form>
</aside>
{%endif%}

{% if search %}
<aside class="single_sidebar_widget search_widget">
                            <form action="#">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder='Search Keyword'
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btns" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                        type="submit">Search
                                </button>
                            </form>
                        </aside>
{%endif%}

{% if instagram_feeds %}
<aside class="single_sidebar_widget search_widget">
                            <form action="#">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder='Search Keyword'
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btns" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                        type="submit">Search
                                </button>
                            </form>
                        </aside>
{%endif%}

templates/blog/search.html
{% extends 'base.html' %}
{% block page_title %}our articles{% endblock %}
{% load static %}
{% load imagefit %}
{% load blog_tags %}
{% block content %}
<main>
    <!--? Hero Start -->
    <div class="slider-area2">
        <div class="slider-height2 d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap hero-cap2 pt-70 text-center">
                            <h2>Search {%if results%}Results{%else%}Page{%endif%}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->
    <!--? Blog Area Start-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        {% if results.has_previous %}
                        <h2>More matching results</h2>
                        {% elif results %}
                        <h2>{% with results.count as total_results %}
                            Found {{ total_results }} result{{ total_results|pluralize }} containing "{{query}}"
                            {% endwith %}</h2>
                        {%else%}
                        <h2>No result found matching "{{query}}"</h2>
                        {% endif %}
                        {% for article in results %}
                        <article class="blog_item">
                            <div class="blog_details">
                                <a class="d-inline-block" href="{{ article.get_absolute_url  }}">
                                    <h2 class="blog-head" style="color: #2d2d2d;">{{article.article_title}}</h2>
                                </a>
                                <p>{{article.article_excerpt|truncatewords_html:30|linebreaks}}</p>
                                <ul class="blog-info-link">
                                    <li>
                                        <a href="{% url 'article:article-by-user' article.article_author.username %}">Written
                                            by
                                            <i class="fa fa-user"></i> {{article.article_author}}</a>
                                    </li>
                                    <li class="tags">
                                        Tags:
                                        {% for tag in article.tags.all %}

                                        <a href="{% url 'article:articles-by-slug' tag.slug %}">
                                            {{ tag.name }}
                                        </a>
                                        {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </li>
                                    <!--                                        <li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>-->
                                </ul>

                            </div>
                        </article>
                        {% endfor %}
                        {% if results %}
                        <h2>Search another term ?</h2>
                        {%endif%}


                        <form action="{%url 'article:search_articles' %}">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control search_form_input"
                                           placeholder='Search Keyword'
                                           onfocus="this.placeholder = ''"
                                           onblur="this.placeholder = 'Search Keyword'" name="query">
                                    <div class="input-group-append">
                                        <button class="btns" type="button"><i class="ti-search search_form_button"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Search
                            </button>
                        </form>
                        {% include "pagination.html" with page_obj=results query_term=query %}

                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <h4 class="widget_title" style="color: #2d2d2d;">Published Articles Statistics</h4>
                            <p>All time: {%total_articles_count%}</p>
                            <p>Today: {%total_articles_today%}</p>
                            <p>This week: {%total_articles_week%}</p>
                            <p>This month: {%total_articles_month%}</p>
                            <p>This year: {%total_articles_year%}</p>

                        </aside>
                        {% show_top_categories 6 %}
                        {% show_most_used_tags 5 %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Area End -->
</main>
{% endblock %}

templates/blog/search_result_ajax.html
{% for article in objects %}
<article class="blog_item">
    <div class="blog_details">
        <a class="d-inline-block" href="{{ article.get_absolute_url  }}">
            <h2 class="blog-head" style="color: #2d2d2d;">{{article.article_title}}</h2>
        </a>
        <p>{{article.article_content|safe|truncatewords_html:30|linebreaks}}</p>
        <ul class="blog-info-link">
            <li>
                <a href="{% url 'article:article-by-user' article.article_author.username %}">Written
                    by
                    <i class="fa fa-user"></i> {{article.article_author.get_full_name}}</a>
            </li>
            <li class="tags">
                Tags:
                {% for tag in article.tags.all %}
                <a href="{% url 'article:articles-by-slug' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </li>
            <!--                                        <li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>-->
        </ul>

    </div>
</article>
{% endfor %}

templates/blog/search_widget.html
<form action="{%url 'article:search_articles' %}">
    <div class="form-group">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder='Search Keyword'
                   onfocus="this.placeholder = ''"
                   onblur="this.placeholder = 'Search Keyword'" name="query">
            <div class="input-group-append">
                <button class="btns" type="button"><i class="ti-search"></i></button>
            </div>
        </div>
    </div>
    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Search
    </button>
</form>