blog/urls.py
from django.urls import path

from . import views
from .rss_feeds import LatestArticlesFeed
from .views import (ArticleDeleteView, ArticleListView, UpdateArticleView,
                    UserArticleListView, search_article)

app_name = 'article'
urlpatterns = [
    path('feed/', LatestArticlesFeed(), name='article_feed'),
    path('search/', search_article, name='search_articles'),
    path('create/', views.create_article, name="create-article"),
    path('<slug:slug>/share/', views.post_share, name='post_share'),
    path('<slug:slug>/update/', UpdateArticleView.as_view(), name="update-post"),
    path('<slug:slug>/delete/', ArticleDeleteView.as_view(), name="delete-post"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.article_detail, name='article_detail'),
    path('all/', ArticleListView.as_view(), name="all-articles"),
    path('all/<str:category>', ArticleListView.as_view(), name="articles-by-category"),
    path('all/<slug:tag>', ArticleListView.as_view(), name="articles-by-slug"),
    path('<str:username>/', UserArticleListView.as_view(), name="article-by-user"),
]

contact/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.contact, name="contact"),
    path('thanks/', views.thanks, name="thanks"),
    path('subscribe/', views.newsletter_signup, name='newsletter'),
]

events/urls.py
from django.contrib import admin
from django.urls import path, include

from events.views import AllEventsList, CreateEventView, EventDetailView, PastEventsList, UpcomingEventsList

urlpatterns = [
    path('events/', AllEventsList.as_view(), name='events'),
    path('events/upcoming', UpcomingEventsList.as_view(), name="future_events"),
    path('events/past', PastEventsList.as_view(), name="past_events"),
    path('events/<int:pk>/<slug:slug>', EventDetailView.as_view(), name="event-details"),
    path('event/add', CreateEventView.as_view(), name="new-event"),
]


mainsite/urls.py
from django.urls import path

from mainsite import views
from mainsite.views import AllGalleryImagesListView

app_name = 'mainsite'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('about/', views.about, name='about-page'),
    path('gallery/', AllGalleryImagesListView.as_view(), name="gallery"),
    path('donate/', views.donate, name='donate'),
    path('upload/', views.upload_images, name='imageuploader'),
    path('webhooks/', views.webhooks, name='webhooks'),
    path('callback/', views.callback, name='callback'),
    path('services/', views.services, name='services'),
    path('privacy-policy/', views.privacy, name='privacy'),
]

contact/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    firstname = models.CharField(max_length=40)
    lastname = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    received = models.BooleanField(default=False)

contact/forms.py
import requests
from django import forms
from django.contrib.auth import get_user_model
from django.forms import ModelForm

from contact.models import Contact
from user.models import Lead
from utils.forms import clean_email


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['firstname', 'lastname', 'email', 'subject', 'message']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        clean_email(email)
        return email


class NewsletterForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Lead
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if get_user_model().objects.get(email):
            raise Exception('Email already registered to another user')
        resp = requests.get(email.split('@')[-1])
        if resp.status_code != 200:
            raise Exception('Email invalid')

blog/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector)
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import DeleteView, ListView, UpdateView
from taggit.models import Tag

from blog.forms import ArticleForm, CommentForm, EmailShareForm, SearchForm
from blog.models import Article, Categories
# Get an instance of a logger
from ext_libs.sendgrid.sengrid import send_email
from utils.views import custom_paginator, get_actual_template

logger = logging.getLogger(__name__)


# Post Page Fxn recreated into a class
class ArticleListView(ListView):
    model = Article
    context_object_name = 'objects'
    ordering = ['-date_created']
    paginate_by = 3
    template_name = 'blog/article_list.html'
    tag = None
    category = None

    def get_queryset(self):
        queryset = Article.published.all()
        if self.kwargs.get('tag'):
            self.tag = get_object_or_404(Tag, slug=self.kwargs.get('tag'))
            queryset = queryset.filter(tags__in=[self.tag])
        if self.kwargs.get('category'):
            queryset = queryset.filter(category__title=self.kwargs.get('category'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = self.tag
        context['posts'] = self.get_queryset()
        context['recent_posts'] = self.get_queryset().order_by("-date_created")[:8]
        return context

    def get_template_names(self):
        template_names = super().get_template_names()
        return get_actual_template(self, 'blog/article_ajax.html') + template_names

    def paginate_queryset(self, queryset, page_size):
        return custom_paginator(self.request, page_size, queryset)


class UserArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'blog/article_list.html'
    context_object_name = 'objects'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(get_user_model(), username=self.kwargs.get('username'))
        articles = Article.objects.filter(article_author=user).order_by('-date_created')
        return articles


def get_similar_articles(article, limit=3):
    article_tags_ids = article.tags.values_list('id', flat=True)
    similar_articles = Article.objects.filter(tags__in=article_tags_ids).exclude(id=article.id)
    return similar_articles.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish_date')[:limit]


def article_detail(request, year, month, day, slug):
    template_name = 'blog/article_detail.html'
    article = get_object_or_404(Article, article_slug=slug,
                                publish_date__year=year,
                                publish_date__month=month,
                                publish_date__day=day)
    comments = article.comments.filter(active=True)
    similar_articles = get_similar_articles(article)
    posted_comment = None
    if request.method == 'POST':
        comment = CommentForm(request.POST)
        if comment.is_valid():
            new_comment = comment.save(commit=False)
            new_comment.post = article
            new_comment.save()
            if new_comment.id:
                messages.info(
                    request, 'Your comment has been posted and is awaiting moderation')
            else:
                messages.error(
                    request, 'Your comment was not posted, try again later')
            return HttpResponseRedirect(request.headers.get('referer'))
        else:
            logger.error(msg=str(comment.errors))
        messages.error(request, 'Form not fully filled, please retry.')
        return HttpResponseRedirect(request.headers.get('referer'))
    else:
        # comment_form = CommentForm()
        return render(request, template_name, {
            'article': article,
            'comments': comments,
            'new_comment': posted_comment,
            'similar': similar_articles,
        })


def search_article(request):
    form = SearchForm()
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    query = request.GET.get('query')
    results = []
    page = request.GET.get('page')
    context = {'form': form,
               'page': page,
               'query': query}
    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = \
                SearchVector('article_title', weight='A') + SearchVector('article_excerpt', weight='C') + \
                SearchVector('article_content', weight='C') + SearchVector('article_author__username', weight='D') + \
                SearchVector('article_author__first_name', weight='B') + SearchVector('article_author__last_name',
                                                                                      weight='B')
            search_query = SearchQuery(query)
            results = Article.published.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.2).order_by('-rank')
        paginator = Paginator(results, 2)
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            if is_ajax:
                return HttpResponse('')
            results = paginator.page(paginator.num_pages)
        if is_ajax:
            context['objects'] = results
            context['query'] = query
            context['pager'] = False
            return render(request, 'blog/search_result_ajax.html', context)
    context['objects'] = results
    return render(request, 'blog/search_page.html', context)


@login_required
def create_article(request):
    template_name = 'blog/article_form.html'

    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)

        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.article_author = request.user
            article.save()

            for category in article_form.cleaned_data['category']:
                new_category_instance, _ = Categories.objects.get_or_create(title=category)
                article.category.add(new_category_instance)

            article_form.save_m2m()
            return redirect('article:all-articles')

        article_errors = article_form.errors
        logger.error(article_errors)
    else:
        article_form = ArticleForm()

    context = {
        'form': article_form,
        'action_to_perform': "create new"
    }
    return render(request, template_name, context)


class UpdateArticleView(UserPassesTestMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/article_form.html'
    slug_url_kwarg = 'slug'
    slug_field = 'article_slug'

    def form_valid(self, form):
        form.instance.article_author = self.request.user
        image_field = form.cleaned_data.get('image_field')
        if isinstance(image_field, InMemoryUploadedFile):
            form.instance.image_field.save(
                image_field.name,
                image_field,
                save=False
            )

        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.article_author:
            return True
        return False

    def get_success_url(self):
        article = self.get_object()
        slug = article.article_slug
        date = article.publish_date

        return reverse('article:article_detail', kwargs={'year': date.year,
                                                         'month': date.month,
                                                         'day': date.day,
                                                         'slug': slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_to_perform'] = "update"
        return context


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    model = Article
    template_name = 'blog/article_confirm_delete.html'
    context_object_name = 'post'
    success_url = 'article:all-articles'
    slug_field = 'article_slug'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.article_author:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        article = self.get_object()
        article.is_deleted = True
        article.save()
        return redirect(self.success_url)


# Create your views here.
@login_required()
def all_post(request):
    post = Article.objects.all()
    return render(request, 'all-post.html', {'post': post})


# Create your views here.
@login_required()
def single_post(request):
    return render(request, 'article_detail.html')


# Create your views here.
def about(request):
    return render(request, 'about.html')


# remove if field later for uuid from calling function
# add option to share pot on FB, Twitter and IG

contact/views.py
import logging

from django.conf import settings
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from honeypot.decorators import check_honeypot

from ext_libs.sendgrid.sengrid import send_email

from .forms import ContactForm, NewsletterForm

logger = logging.getLogger(__name__)


@check_honeypot
def contact(request):
    contact_form = ContactForm()
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            new_message = contact_form.save(commit=False)
            context = {
                'sender': contact_form.data.get('email'),
                'fname': contact_form.data.get('firstname'),
                'lname': contact_form.data.get('lastname'),
                'detail': contact_form.data.get('message'),
                'title': contact_form.data.get('subject'),
            }
            try:
                send_email(source=settings.EMAIL_HOST_USER, destination=settings.GMAIL_EMAIL,
                           subject='FEEDSOMEONE CONTACT FORM', content=render_to_string('new_email.html', context))
                new_message.received = True
            except Exception as e:
                new_message.received = False
                logger.log(level=logging.ERROR, msg=f'Error sending mail: {str(e)}')
            finally:
                new_message.save()
            data = {
                'subject': 'Thank You!',
                'title': 'Feedsomeone - contact form response',
                'msg': """<strong>Your email has been received</strong> and you will be replied to shortly."""
            }
            return render(request, 'thank-you.html', data)
        else:
            logger.log(msg='please make sure all fields are filled appropriately', level=logging.ERROR)
            errors = contact_form.errors
            return render(request, 'contact.html', {'form': contact_form, 'errors': errors})
    else:
        return render(request, 'contact.html', {'form': contact_form})


def thanks(request):
    return render(request, 'thank-you.html')


@check_honeypot
def newsletter_signup(request):
    new_lead = NewsletterForm(request.POST)
    if new_lead.is_valid():
        try:
            new_lead.save(commit=False)
            send_email(source=settings.EMAIL_HOST_USER,
                       destination=new_lead.data.get('email'),
                       subject='Welcome to the family',
                       content='''
                       Thank you for subscribing to our newsletter,
                        we will be sending you updates on our events,
                        causes, outreaches, and articles from our team
                        of brilliant volunteer writers. <br><br>Regards<br>
                        Oluwafemi Ebenezer<Founder>
                        ''',
                       plain=True
                       )
        except Exception as e:
            print('AAAA')
            # handle already subscribed exception or any other exception
            print('email cannot be added', str(e))
        else:
            # send welcome email for campaign
            print('BBB')
            new_lead.save()
        finally:
            print('CCC')
            return redirect('/')

templates/create_username.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_title %}Set username{% endblock %}
{% block content %}
<div id="colorlib-main">
    <div id="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="row d-flex mb-5 contact-info">
                    <div class="col-sm-12">
                        <form method="POST" name="login" class="mt-5 ml-5 mr-5" style="padding: 10% 15% !important;
                        align-content: center !important;">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Create your custom username</legend>
                                <div id="contentform">
                                    {{ form.username|as_crispy_field }}
                                    <div id="availability-status"></div>
                                </div>
                            </fieldset>
                            <div class="form-group">
                                <input type="submit" class="btn btn-secondary" value="Create username">
                            </div>
                        </form>
                        <div class="border-top pt-3">
                            <small class="text-muted mt-5 ml-5">
                                Don't have an account? <a href="{% url 'register' %}" style="color: #6ec54d;">check availability</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
  // Function to check username availability using AJAX
  function checkUsernameAvailability() {
    const usernameInput = document.querySelector('#id_username');
    const availabilityStatus = document.querySelector('#availability-status');

    const username = usernameInput.value.trim();

    if (username.length < 4) {
          pass_len = false
          availabilityStatus.textContent = 'Username is too short';
          availabilityStatus.style.color = 'red';
    }
    else{pass_len = true}

    const formData = new FormData();
    formData.append('username', username);

    // Send AJAX request to check username availability
    fetch("{% url 'check_username_availability' %}", {
      method: 'POST',
      headers: {
        'X-CSRFToken': '{{ csrf_token }}',
      },
      body: formData,
    })
      .then((response) => response.json())
      .then((data) => {
        // Display the availability status
        if (pass_len == true){
        if (data.available) {
          availabilityStatus.textContent = 'Username is available.';
          availabilityStatus.style.color = 'green';
        } else {
          availabilityStatus.textContent = 'Username is already taken. Please choose a different one.';
          availabilityStatus.style.color = 'red';
        }}
      });
  }

  // Add event listener to the username input field
  const usernameInput = document.querySelector('#id_username');
  usernameInput.addEventListener('input', checkUsernameAvailability);
</script>

{% endblock %}

templates/index.html
{% load cms_tags sekizai_tags %}
<html>
    <head>
        <title>{% page_attribute "page_title" %}</title>
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        {% placeholder "content" %}
        {% render_block "js" %}
    </body>
</html>

templates/newsletter_form.html
<form id="subscribenow" class="footer-newsletter"
      action="{% url 'newsletter'%}"
      method="post" target="_blank" novalidate>
    {% csrf_token %}
    <input class="input" id="footer-input" type="email" name="email" placeholder="Enter your email">
    <button class="primary-button">Subscribe</button>
</form>

templates/pagination.html
{% if page_obj.paginator.num_pages > 1 %}
<nav class="blog-pagination justify-content-center d-flex">
    <ul class="pagination mb-4">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="{%if query_term%}?query={{query_term}}&{%endif%}&page=1" class="page-link" aria-label="Previous">First</a>
        </li>
        <li class="page-item">
            <a href="{%if query_term%}?query={{query_term}}&{%endif%}?page={{page_obj.previous_page_number}}"
               class="page-link"
               aria-label="Previous"><i class="ti-angle-left"></i></a>
        </li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
        {% if page_obj.number == page %}
        <li class="page-item active">
            <a class="page-link" href="{%if query_term%}?query={{query_term}}&{%endif%}?page={{page}}">{{page}}</a>
        </li>
        {% elif page > page_obj.number|add:'-2' and page < page_obj.number|add:'2' %}
        <li class="page-item"><a class="page-link"
                                 href="{%if query_term%}?query={{query_term}}&{%endif%}?page={{page}}">{{page}}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="{%if query_term%}?query={{query_term}}&{%endif%}?page={{ page_obj.next_page_number }}"
               class="page-link"
               aria-label="Next">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        <li class="page-item">
            <a href="{%if query_term%}?query={{query_term}}&{%endif%}?page={{ page_obj.paginator.num_pages }}"
               class="page-link">Last</a>
        </li>
        {% endif %}
    </ul>
</nav>
{%endif%}

templates/robot_response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration invalid</title>
</head>
<body>
    {% if is_robot %}
        <h1>Hi, you are robot</h1>
        {% else %}
        <h1>Hi {{ name }}</h1>
        {% endif %}
        <p>You will be redirected into homepage</p>


        <script charset="utf-8">
            setTimeout(function(){
                window.location.href = "{% url 'mainsite:homepage' %}"
            }, 2000)
        </script>

</body>
</html>

templates/upload_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload File</title>
    <style>
        /* CSS styles go here */
        body {
            font-family: Arial, sans-serif;
        }

        .container {
            max-width: 500px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f2f2f2;
            border-radius: 5px;
        }

        .form-field {
            margin-bottom: 10px;
        }

        .form-field label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .form-field input[type="file"] {
            margin-top: 5px;
        }

        .form-field input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Upload File</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-field">
                <label>{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <input type="submit" value="Upload">
        </form>
    </div>
</body>
</html>

templates/upload_images.html
{% load static %}
{% block css %}
    <!-- jQuery Upload Files -->
    <link rel="stylesheet" href="{% static 'jQuery-File-Upload/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fileupload.css' %}">
{% endblock %}
<div class="row fileupload-buttonbar">
          <div class="col-lg-7">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
              <i class="glyphicon glyphicon-plus"></i>
              <span>Add files...</span>
              <input type="file" name="files[]" multiple="">
            </span>
            <button type="submit" class="btn btn-primary start">
              <i class="glyphicon glyphicon-upload"></i>
              <span>Start upload</span>
            </button>
            <button type="reset" class="btn btn-warning cancel">
              <i class="glyphicon glyphicon-ban-circle"></i>
              <span>Cancel upload</span>
            </button>
            <button type="button" class="btn btn-danger delete">
              <i class="glyphicon glyphicon-trash"></i>
              <span>Delete selected</span>
            </button>
            <input type="checkbox" class="toggle">
            <!-- The global file processing state -->
            <span class="fileupload-process"></span>
          </div>
          <!-- The global progress state -->
          <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
              <div class="progress-bar progress-bar-success" style="width: 0%;"></div>
            </div>
            <!-- The extended global progress state -->
            <div class="progress-extended">&nbsp;</div>
          </div>
        </div>
{% block js %}
    <!-- jQuery Upload Files -->
    <script src="{% static 'js/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'js/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'js/jquery.fileupload.js' %}"></script>
{% endblock %}